name: Java CI with Maven
on: 
  # Jenkins Build Trigger: Polling SCM every 4 minutes for changes
  # GitHub Action: Trigger on push to master branch.
  push:
    branches: [ "master" ]
  workflow_dispatch: # Allow you to manually trigger work flow

jobs:
  build:
    # GitHub-hosted Runner. 
    # GHES, use our own runner.
    runs-on: ubuntu-latest

    steps:
    
    # Jenkins Source Code Mangement: SVN 
    # GHA: Check out project from Git Repo
    - uses: actions/checkout@v4 
      with:
        fetch-depth: '0' # To get all commit history

    # # Shared settings.xml for recondo projects
    # # GlobalRecondoMavenSettings.xml 
    # - name: Checkout shared-settings repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: RickyHuangWaystar/shared-settings
    #     path: shared-settings
    
    # - name: Copy settings.xml to ~/.m2
    #   run: |
    #     mkdir -p ~/.m2
    #     cp shared-settings/settings.xml ~/.m2/settings.xml
    # - name: Checkout shared-settings repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: RickyHuangWaystar/shared-settings
    #     path: shared-settings
    
    # - name: Copy settings.xml to ~/.m2
    #   run: |
    #     mkdir -p ~/.m2
    #     cp shared-settings/settings.xml ~/.m2/settings.xml
        
    # Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4 
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    #Cache to improve the workflow execution time    
    # - name: Cache Maven packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.m2
    #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: ${{ runner.os }}-m2
         
    # Jenkins Prestep:
    # GET_SVN_LOG.sh - script gets last 90 days of checkins and writes them to a 
    # file called: "svn_" + {service name} + "." + {svn revision #} + ".log"
    # GitHub Actions: Script to fetch commits for the last 90 days and write to a log file
    #- name: Get Commits for the Last 90 Days 
    #  run: |
    #     START_DATE=$(date +"%Y-%m-%d" -d "-90 days")
    #     git log --since="$START_DATE" --pretty=format:"Commit: %H%nAuthor: %an <%ae>%nDate: %ad%nMessage: %s%nChanged files:" --date=short --name-only | awk 'BEGIN {FS="n"} {if ($0 ~ /Changed files:/) {print $0} else {print " "$0}}' >  ${{ github.event.repository.name }}_commits_last_90_days.log
    #- name: Upload Commit Log as Artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #   name: ${{ github.event.repository.name }} Commits Last 90 Days Log
    #   path: ${{ github.event.repository.name }}_commits_last_90_days.log
    
    # Jenkins: clean install -U
    # Build, test, code coverage, depdency check
    - name: Build with Maven
      run: mvn clean install -U

    # JENKINS: Post steps: Run only if build is succeeds
    # By default, a GitHub Actions workflow will stop if a step fails
    # JENKINS: Set email notifcation to specific receipents.
    # GITHUB: Only sends email to the receipent who triggered the workflow.

    # Post-build Actions: 
    # 1. Deploy artifacts to Artifactory 
    # 2. Record Code Coverage Report
    # 3. Publish Dependency Check Results

   # - name: Deploy artifacts to Artifactory
   #   run: mvn deploy

    - name: Upload JaCoCo Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: JaCoCo Code Coverage Report
        path: target/site/jacoco/
        if-no-files-found: error
        retention-days: 90   # DEFAULT 90 days, Enterprise can confiture up to 400 days
   
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: Dependency Check Report
        path: target/dependency-check-report.html

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/testCoveragejacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60 
    
