name: Java CI with Maven

# TRIGGERS
on: 
  # Jenkins: Polling SCM every 4 minutes for changes
  # Trigger on push or pr to master branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Run manually

# JOBS
jobs:
  build:
    # GitHub-hosted Runner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
      with:
        fetch-depth: '0'
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Get Commits for the Last 7 Days
        
      run: |
        git log --since='7 days ago' --pretty=format:'%h %an %s' > commits.txt


    - name: Upload Commit Log as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: commits_last_90_days
        path: commits.txt

        
        
    # Cache to improve the workflow execution time    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Jenkins: clean install -U
    # TODO What is GlobalRecondoMavenSettings.xml
    # BUILD, RUN UNIT TEST, RUN JaCoCo, Run Dependency Check
    - name: Build with Maven
      run: mvn clean install -U

    # JENKINS: Post steps: Run only if build is succee
    # By default, a GitHub Actions workflow will stop if a step fails
    # JENKINS: Set email notifcation to specific receipents.
    # GITHUB: Only sends email to the receipent who triggered the workflow.

    # Code Coverage Report
    - name: Upload JaCoCo Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: JaCoCo Code Coverage Report
        path: target/site/jacoco/

    # Depdendency Vulnerability Analysis
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: Dependency Check Report
        path: target/dependency-check-report.html
        if-no-files-found: error
        retention-days: 90

    # TODO DEPLOY ARTIFACTS to Artifcatory

